model:
  name: "resnet50"
  weights: 'micronet'

dataloader:
  batch_size: 4
  shuffle: True
  num_workers: 1

training:
  epochs: 500
  learning_rate: 5e-5
  bce_weight: 0.5
  patience: 30
  checkpoint_interval: 10
  checkpoint_dir: '/data/horse/ws/rana575h-model_training_microseg/checkpoints_6Jul/'

data:
  base_path: "./Super1"

dirs:
  plots_dir: '/data/horse/ws/rana575h-model_training_microseg/plots'
  loss_logs: '/data/horse/ws/rana575h-model_training_microseg/loss_logs'
  tensorboard_logs: '/data/horse/ws/rana575h-model_training_microseg/tb_logs'