model:
  name: "resnet50"
  weights: 'micronet'

dataloader:
  batch_size: 4
  shuffle: True
  num_workers: 1

training:
  epochs: 10
  learning_rate: 2e-4
  bce_weight: 0.5
  patience: 2
  checkpoint_interval: 2

data:
  base_path: "./Super1"
  val_split: 0.2